### ISSUE TITLE
how to change the gold boots icon?

### ISSUE THREAD

**Issue by LoreWasTaken** [DuncanRuns/AutoResetMod#4]
Probably this is a stupid question but, is there a way like creating a resource pack that changes the gold boots icon with something else? If yes how do i do it? Thanks in advance.

**Comment by DuncanRuns** [comment]
Sorry for the late response.
The mod uses the golden boots texture, so changing the golden boots texture would also change the button.
You unfortunately cannot change which item the button uses.
